/**
 * IPC Namespace Helpers — Architecture improvement 3.3
 *
 * Provides a namespace-grouped view of IPC channels and type-safe helpers.
 * The flat IPC_CHANNELS object is preserved for backward compatibility;
 * this module adds structure on top without breaking existing consumers.
 *
 * Usage:
 *   import { IPC_NS, getChannelsByNamespace } from '@shared/constants/ipc-namespaces';
 *
 *   // Typed namespace access
 *   ipcMain.handle(IPC_NS.project.ADD, ...);
 *   ipcMain.handle(IPC_NS.terminal.CREATE, ...);
 *
 *   // Get all channels for a domain (useful for auto-discovery / logging)
 *   const terminalChannels = getChannelsByNamespace('terminal');
 */

import { IPC_CHANNELS } from './ipc';

// ============================================
// Channel value type
// ============================================

type ChannelValue = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

// ============================================
// Namespace-grouped view
// ============================================

export const IPC_NS = {
  project: {
    ADD: IPC_CHANNELS.PROJECT_ADD,
    REMOVE: IPC_CHANNELS.PROJECT_REMOVE,
    LIST: IPC_CHANNELS.PROJECT_LIST,
    UPDATE_SETTINGS: IPC_CHANNELS.PROJECT_UPDATE_SETTINGS,
    INITIALIZE: IPC_CHANNELS.PROJECT_INITIALIZE,
    CHECK_VERSION: IPC_CHANNELS.PROJECT_CHECK_VERSION,
  },

  tabState: {
    GET: IPC_CHANNELS.TAB_STATE_GET,
    SAVE: IPC_CHANNELS.TAB_STATE_SAVE,
  },

  kanban: {
    PREFS_GET: IPC_CHANNELS.KANBAN_PREFS_GET,
    PREFS_SAVE: IPC_CHANNELS.KANBAN_PREFS_SAVE,
  },

  task: {
    LIST: IPC_CHANNELS.TASK_LIST,
    CREATE: IPC_CHANNELS.TASK_CREATE,
    DELETE: IPC_CHANNELS.TASK_DELETE,
    UPDATE: IPC_CHANNELS.TASK_UPDATE,
    START: IPC_CHANNELS.TASK_START,
    STOP: IPC_CHANNELS.TASK_STOP,
    REVIEW: IPC_CHANNELS.TASK_REVIEW,
    UPDATE_STATUS: IPC_CHANNELS.TASK_UPDATE_STATUS,
    RECOVER_STUCK: IPC_CHANNELS.TASK_RECOVER_STUCK,
    CHECK_RUNNING: IPC_CHANNELS.TASK_CHECK_RUNNING,
    RESUME_PAUSED: IPC_CHANNELS.TASK_RESUME_PAUSED,
    LOAD_IMAGE_THUMBNAIL: IPC_CHANNELS.TASK_LOAD_IMAGE_THUMBNAIL,
    ARCHIVE: IPC_CHANNELS.TASK_ARCHIVE,
    UNARCHIVE: IPC_CHANNELS.TASK_UNARCHIVE,
    CLEAR_STAGED_STATE: IPC_CHANNELS.TASK_CLEAR_STAGED_STATE,

    // Worktree
    WORKTREE_STATUS: IPC_CHANNELS.TASK_WORKTREE_STATUS,
    WORKTREE_DIFF: IPC_CHANNELS.TASK_WORKTREE_DIFF,
    WORKTREE_MERGE: IPC_CHANNELS.TASK_WORKTREE_MERGE,
    WORKTREE_MERGE_PREVIEW: IPC_CHANNELS.TASK_WORKTREE_MERGE_PREVIEW,
    WORKTREE_DISCARD: IPC_CHANNELS.TASK_WORKTREE_DISCARD,
    WORKTREE_DISCARD_ORPHAN: IPC_CHANNELS.TASK_WORKTREE_DISCARD_ORPHAN,
    WORKTREE_CREATE_PR: IPC_CHANNELS.TASK_WORKTREE_CREATE_PR,
    WORKTREE_OPEN_IN_IDE: IPC_CHANNELS.TASK_WORKTREE_OPEN_IN_IDE,
    WORKTREE_OPEN_IN_TERMINAL: IPC_CHANNELS.TASK_WORKTREE_OPEN_IN_TERMINAL,
    WORKTREE_DETECT_TOOLS: IPC_CHANNELS.TASK_WORKTREE_DETECT_TOOLS,
    LIST_WORKTREES: IPC_CHANNELS.TASK_LIST_WORKTREES,

    // Events (main → renderer)
    PROGRESS: IPC_CHANNELS.TASK_PROGRESS,
    ERROR: IPC_CHANNELS.TASK_ERROR,
    LOG: IPC_CHANNELS.TASK_LOG,
    STATUS_CHANGE: IPC_CHANNELS.TASK_STATUS_CHANGE,
    EXECUTION_PROGRESS: IPC_CHANNELS.TASK_EXECUTION_PROGRESS,

    // Phase logs
    LOGS_GET: IPC_CHANNELS.TASK_LOGS_GET,
    LOGS_WATCH: IPC_CHANNELS.TASK_LOGS_WATCH,
    LOGS_UNWATCH: IPC_CHANNELS.TASK_LOGS_UNWATCH,
    LOGS_CHANGED: IPC_CHANNELS.TASK_LOGS_CHANGED,
    LOGS_STREAM: IPC_CHANNELS.TASK_LOGS_STREAM,
    MERGE_PROGRESS: IPC_CHANNELS.TASK_MERGE_PROGRESS,
  },

  terminal: {
    CREATE: IPC_CHANNELS.TERMINAL_CREATE,
    DESTROY: IPC_CHANNELS.TERMINAL_DESTROY,
    INPUT: IPC_CHANNELS.TERMINAL_INPUT,
    RESIZE: IPC_CHANNELS.TERMINAL_RESIZE,
    INVOKE_CLAUDE: IPC_CHANNELS.TERMINAL_INVOKE_CLAUDE,
    GENERATE_NAME: IPC_CHANNELS.TERMINAL_GENERATE_NAME,
    SET_TITLE: IPC_CHANNELS.TERMINAL_SET_TITLE,
    SET_WORKTREE_CONFIG: IPC_CHANNELS.TERMINAL_SET_WORKTREE_CONFIG,

    // Session management
    GET_SESSIONS: IPC_CHANNELS.TERMINAL_GET_SESSIONS,
    RESTORE_SESSION: IPC_CHANNELS.TERMINAL_RESTORE_SESSION,
    CLEAR_SESSIONS: IPC_CHANNELS.TERMINAL_CLEAR_SESSIONS,
    RESUME_CLAUDE: IPC_CHANNELS.TERMINAL_RESUME_CLAUDE,
    ACTIVATE_DEFERRED_RESUME: IPC_CHANNELS.TERMINAL_ACTIVATE_DEFERRED_RESUME,
    GET_SESSION_DATES: IPC_CHANNELS.TERMINAL_GET_SESSION_DATES,
    GET_SESSIONS_FOR_DATE: IPC_CHANNELS.TERMINAL_GET_SESSIONS_FOR_DATE,
    RESTORE_FROM_DATE: IPC_CHANNELS.TERMINAL_RESTORE_FROM_DATE,
    CHECK_PTY_ALIVE: IPC_CHANNELS.TERMINAL_CHECK_PTY_ALIVE,
    UPDATE_DISPLAY_ORDERS: IPC_CHANNELS.TERMINAL_UPDATE_DISPLAY_ORDERS,

    // Worktree ops
    WORKTREE_CREATE: IPC_CHANNELS.TERMINAL_WORKTREE_CREATE,
    WORKTREE_REMOVE: IPC_CHANNELS.TERMINAL_WORKTREE_REMOVE,
    WORKTREE_LIST: IPC_CHANNELS.TERMINAL_WORKTREE_LIST,
    WORKTREE_LIST_OTHER: IPC_CHANNELS.TERMINAL_WORKTREE_LIST_OTHER,

    // Events (main → renderer)
    OUTPUT: IPC_CHANNELS.TERMINAL_OUTPUT,
    EXIT: IPC_CHANNELS.TERMINAL_EXIT,
    TITLE_CHANGE: IPC_CHANNELS.TERMINAL_TITLE_CHANGE,
    WORKTREE_CONFIG_CHANGE: IPC_CHANNELS.TERMINAL_WORKTREE_CONFIG_CHANGE,
    CLAUDE_SESSION: IPC_CHANNELS.TERMINAL_CLAUDE_SESSION,
    PENDING_RESUME: IPC_CHANNELS.TERMINAL_PENDING_RESUME,
    RATE_LIMIT: IPC_CHANNELS.TERMINAL_RATE_LIMIT,
    OAUTH_TOKEN: IPC_CHANNELS.TERMINAL_OAUTH_TOKEN,
    AUTH_CREATED: IPC_CHANNELS.TERMINAL_AUTH_CREATED,
    OAUTH_CODE_NEEDED: IPC_CHANNELS.TERMINAL_OAUTH_CODE_NEEDED,
    OAUTH_CODE_SUBMIT: IPC_CHANNELS.TERMINAL_OAUTH_CODE_SUBMIT,
    CLAUDE_BUSY: IPC_CHANNELS.TERMINAL_CLAUDE_BUSY,
    CLAUDE_EXIT: IPC_CHANNELS.TERMINAL_CLAUDE_EXIT,
    ONBOARDING_COMPLETE: IPC_CHANNELS.TERMINAL_ONBOARDING_COMPLETE,
    PROFILE_CHANGED: IPC_CHANNELS.TERMINAL_PROFILE_CHANGED,
  },

  claude: {
    PROFILES_GET: IPC_CHANNELS.CLAUDE_PROFILES_GET,
    PROFILE_SAVE: IPC_CHANNELS.CLAUDE_PROFILE_SAVE,
    PROFILE_DELETE: IPC_CHANNELS.CLAUDE_PROFILE_DELETE,
    PROFILE_RENAME: IPC_CHANNELS.CLAUDE_PROFILE_RENAME,
    PROFILE_SET_ACTIVE: IPC_CHANNELS.CLAUDE_PROFILE_SET_ACTIVE,
    PROFILE_SWITCH: IPC_CHANNELS.CLAUDE_PROFILE_SWITCH,
    PROFILE_INITIALIZE: IPC_CHANNELS.CLAUDE_PROFILE_INITIALIZE,
    PROFILE_SET_TOKEN: IPC_CHANNELS.CLAUDE_PROFILE_SET_TOKEN,
    PROFILE_AUTHENTICATE: IPC_CHANNELS.CLAUDE_PROFILE_AUTHENTICATE,
    PROFILE_VERIFY_AUTH: IPC_CHANNELS.CLAUDE_PROFILE_VERIFY_AUTH,
    PROFILE_AUTO_SWITCH_SETTINGS: IPC_CHANNELS.CLAUDE_PROFILE_AUTO_SWITCH_SETTINGS,
    PROFILE_UPDATE_AUTO_SWITCH: IPC_CHANNELS.CLAUDE_PROFILE_UPDATE_AUTO_SWITCH,
    PROFILE_FETCH_USAGE: IPC_CHANNELS.CLAUDE_PROFILE_FETCH_USAGE,
    PROFILE_GET_BEST_PROFILE: IPC_CHANNELS.CLAUDE_PROFILE_GET_BEST_PROFILE,
    SDK_RATE_LIMIT: IPC_CHANNELS.CLAUDE_SDK_RATE_LIMIT,
    AUTH_FAILURE: IPC_CHANNELS.CLAUDE_AUTH_FAILURE,
    RETRY_WITH_PROFILE: IPC_CHANNELS.CLAUDE_RETRY_WITH_PROFILE,

    // Usage monitoring
    USAGE_UPDATED: IPC_CHANNELS.USAGE_UPDATED,
    USAGE_REQUEST: IPC_CHANNELS.USAGE_REQUEST,
    ALL_PROFILES_USAGE_REQUEST: IPC_CHANNELS.ALL_PROFILES_USAGE_REQUEST,
    ALL_PROFILES_USAGE_UPDATED: IPC_CHANNELS.ALL_PROFILES_USAGE_UPDATED,
    PROACTIVE_SWAP_NOTIFICATION: IPC_CHANNELS.PROACTIVE_SWAP_NOTIFICATION,
  },

  account: {
    PRIORITY_GET: IPC_CHANNELS.ACCOUNT_PRIORITY_GET,
    PRIORITY_SET: IPC_CHANNELS.ACCOUNT_PRIORITY_SET,
  },

  settings: {
    GET: IPC_CHANNELS.SETTINGS_GET,
    SAVE: IPC_CHANNELS.SETTINGS_SAVE,
    GET_CLI_TOOLS_INFO: IPC_CHANNELS.SETTINGS_GET_CLI_TOOLS_INFO,
    CLAUDE_CODE_GET_ONBOARDING_STATUS: IPC_CHANNELS.SETTINGS_CLAUDE_CODE_GET_ONBOARDING_STATUS,
  },

  profiles: {
    GET: IPC_CHANNELS.PROFILES_GET,
    SAVE: IPC_CHANNELS.PROFILES_SAVE,
    UPDATE: IPC_CHANNELS.PROFILES_UPDATE,
    DELETE: IPC_CHANNELS.PROFILES_DELETE,
    SET_ACTIVE: IPC_CHANNELS.PROFILES_SET_ACTIVE,
    TEST_CONNECTION: IPC_CHANNELS.PROFILES_TEST_CONNECTION,
    TEST_CONNECTION_CANCEL: IPC_CHANNELS.PROFILES_TEST_CONNECTION_CANCEL,
    DISCOVER_MODELS: IPC_CHANNELS.PROFILES_DISCOVER_MODELS,
    DISCOVER_MODELS_CANCEL: IPC_CHANNELS.PROFILES_DISCOVER_MODELS_CANCEL,
  },

  dialog: {
    SELECT_DIRECTORY: IPC_CHANNELS.DIALOG_SELECT_DIRECTORY,
    CREATE_PROJECT_FOLDER: IPC_CHANNELS.DIALOG_CREATE_PROJECT_FOLDER,
    GET_DEFAULT_PROJECT_LOCATION: IPC_CHANNELS.DIALOG_GET_DEFAULT_PROJECT_LOCATION,
  },

  shell: {
    OPEN_EXTERNAL: IPC_CHANNELS.SHELL_OPEN_EXTERNAL,
    OPEN_TERMINAL: IPC_CHANNELS.SHELL_OPEN_TERMINAL,
    OPEN_TERMINAL_WITH_COMMAND: IPC_CHANNELS.SHELL_OPEN_TERMINAL_WITH_COMMAND,
  },

  roadmap: {
    GET: IPC_CHANNELS.ROADMAP_GET,
    GET_STATUS: IPC_CHANNELS.ROADMAP_GET_STATUS,
    SAVE: IPC_CHANNELS.ROADMAP_SAVE,
    GENERATE: IPC_CHANNELS.ROADMAP_GENERATE,
    GENERATE_WITH_COMPETITOR: IPC_CHANNELS.ROADMAP_GENERATE_WITH_COMPETITOR,
    REFRESH: IPC_CHANNELS.ROADMAP_REFRESH,
    STOP: IPC_CHANNELS.ROADMAP_STOP,
    UPDATE_FEATURE: IPC_CHANNELS.ROADMAP_UPDATE_FEATURE,
    CONVERT_TO_SPEC: IPC_CHANNELS.ROADMAP_CONVERT_TO_SPEC,
    PROGRESS: IPC_CHANNELS.ROADMAP_PROGRESS,
    COMPLETE: IPC_CHANNELS.ROADMAP_COMPLETE,
    ERROR: IPC_CHANNELS.ROADMAP_ERROR,
    STOPPED: IPC_CHANNELS.ROADMAP_STOPPED,
    PROGRESS_SAVE: IPC_CHANNELS.ROADMAP_PROGRESS_SAVE,
    PROGRESS_LOAD: IPC_CHANNELS.ROADMAP_PROGRESS_LOAD,
    PROGRESS_CLEAR: IPC_CHANNELS.ROADMAP_PROGRESS_CLEAR,
  },

  context: {
    GET: IPC_CHANNELS.CONTEXT_GET,
    REFRESH_INDEX: IPC_CHANNELS.CONTEXT_REFRESH_INDEX,
    MEMORY_STATUS: IPC_CHANNELS.CONTEXT_MEMORY_STATUS,
    SEARCH_MEMORIES: IPC_CHANNELS.CONTEXT_SEARCH_MEMORIES,
    GET_MEMORIES: IPC_CHANNELS.CONTEXT_GET_MEMORIES,
  },

  env: {
    GET: IPC_CHANNELS.ENV_GET,
    UPDATE: IPC_CHANNELS.ENV_UPDATE,
    CHECK_CLAUDE_AUTH: IPC_CHANNELS.ENV_CHECK_CLAUDE_AUTH,
    INVOKE_CLAUDE_SETUP: IPC_CHANNELS.ENV_INVOKE_CLAUDE_SETUP,
  },

  ideation: {
    GET: IPC_CHANNELS.IDEATION_GET,
    GENERATE: IPC_CHANNELS.IDEATION_GENERATE,
    REFRESH: IPC_CHANNELS.IDEATION_REFRESH,
    STOP: IPC_CHANNELS.IDEATION_STOP,
    UPDATE_IDEA: IPC_CHANNELS.IDEATION_UPDATE_IDEA,
    CONVERT_TO_TASK: IPC_CHANNELS.IDEATION_CONVERT_TO_TASK,
    DISMISS: IPC_CHANNELS.IDEATION_DISMISS,
    DISMISS_ALL: IPC_CHANNELS.IDEATION_DISMISS_ALL,
    ARCHIVE: IPC_CHANNELS.IDEATION_ARCHIVE,
    DELETE: IPC_CHANNELS.IDEATION_DELETE,
    DELETE_MULTIPLE: IPC_CHANNELS.IDEATION_DELETE_MULTIPLE,
    PROGRESS: IPC_CHANNELS.IDEATION_PROGRESS,
    LOG: IPC_CHANNELS.IDEATION_LOG,
    COMPLETE: IPC_CHANNELS.IDEATION_COMPLETE,
    ERROR: IPC_CHANNELS.IDEATION_ERROR,
    STOPPED: IPC_CHANNELS.IDEATION_STOPPED,
    TYPE_COMPLETE: IPC_CHANNELS.IDEATION_TYPE_COMPLETE,
    TYPE_FAILED: IPC_CHANNELS.IDEATION_TYPE_FAILED,
  },

  linear: {
    GET_TEAMS: IPC_CHANNELS.LINEAR_GET_TEAMS,
    GET_PROJECTS: IPC_CHANNELS.LINEAR_GET_PROJECTS,
    GET_ISSUES: IPC_CHANNELS.LINEAR_GET_ISSUES,
    IMPORT_ISSUES: IPC_CHANNELS.LINEAR_IMPORT_ISSUES,
    CHECK_CONNECTION: IPC_CHANNELS.LINEAR_CHECK_CONNECTION,
  },

  azureDevOps: {
    GET_PROJECTS: IPC_CHANNELS.AZURE_DEVOPS_GET_PROJECTS,
    GET_WORK_ITEMS: IPC_CHANNELS.AZURE_DEVOPS_GET_WORK_ITEMS,
    IMPORT_WORK_ITEMS: IPC_CHANNELS.AZURE_DEVOPS_IMPORT_WORK_ITEMS,
    CHECK_CONNECTION: IPC_CHANNELS.AZURE_DEVOPS_CHECK_CONNECTION,
    LIST_REPOSITORIES: IPC_CHANNELS.AZURE_DEVOPS_LIST_REPOSITORIES,
    DETECT_REPOSITORY: IPC_CHANNELS.AZURE_DEVOPS_DETECT_REPOSITORY,
  },

  jira: {
    GET_ISSUES: IPC_CHANNELS.JIRA_GET_ISSUES,
    CHECK_CONNECTION: IPC_CHANNELS.JIRA_CHECK_CONNECTION,
  },

  github: {
    GET_REPOSITORIES: IPC_CHANNELS.GITHUB_GET_REPOSITORIES,
    GET_ISSUES: IPC_CHANNELS.GITHUB_GET_ISSUES,
    GET_ISSUE: IPC_CHANNELS.GITHUB_GET_ISSUE,
    GET_ISSUE_COMMENTS: IPC_CHANNELS.GITHUB_GET_ISSUE_COMMENTS,
    CHECK_CONNECTION: IPC_CHANNELS.GITHUB_CHECK_CONNECTION,
    INVESTIGATE_ISSUE: IPC_CHANNELS.GITHUB_INVESTIGATE_ISSUE,
    IMPORT_ISSUES: IPC_CHANNELS.GITHUB_IMPORT_ISSUES,
    CREATE_RELEASE: IPC_CHANNELS.GITHUB_CREATE_RELEASE,

    // OAuth
    CHECK_CLI: IPC_CHANNELS.GITHUB_CHECK_CLI,
    CHECK_AUTH: IPC_CHANNELS.GITHUB_CHECK_AUTH,
    START_AUTH: IPC_CHANNELS.GITHUB_START_AUTH,
    GET_TOKEN: IPC_CHANNELS.GITHUB_GET_TOKEN,
    GET_USER: IPC_CHANNELS.GITHUB_GET_USER,
    LIST_USER_REPOS: IPC_CHANNELS.GITHUB_LIST_USER_REPOS,
    DETECT_REPO: IPC_CHANNELS.GITHUB_DETECT_REPO,
    GET_BRANCHES: IPC_CHANNELS.GITHUB_GET_BRANCHES,
    CREATE_REPO: IPC_CHANNELS.GITHUB_CREATE_REPO,
    ADD_REMOTE: IPC_CHANNELS.GITHUB_ADD_REMOTE,
    LIST_ORGS: IPC_CHANNELS.GITHUB_LIST_ORGS,

    // Events
    AUTH_DEVICE_CODE: IPC_CHANNELS.GITHUB_AUTH_DEVICE_CODE,
    AUTH_CHANGED: IPC_CHANNELS.GITHUB_AUTH_CHANGED,
    INVESTIGATION_PROGRESS: IPC_CHANNELS.GITHUB_INVESTIGATION_PROGRESS,
    INVESTIGATION_COMPLETE: IPC_CHANNELS.GITHUB_INVESTIGATION_COMPLETE,
    INVESTIGATION_ERROR: IPC_CHANNELS.GITHUB_INVESTIGATION_ERROR,
  },

  changelog: {
    GET_DONE_TASKS: IPC_CHANNELS.CHANGELOG_GET_DONE_TASKS,
    LOAD_TASK_SPECS: IPC_CHANNELS.CHANGELOG_LOAD_TASK_SPECS,
    GENERATE: IPC_CHANNELS.CHANGELOG_GENERATE,
    SAVE: IPC_CHANNELS.CHANGELOG_SAVE,
    READ_EXISTING: IPC_CHANNELS.CHANGELOG_READ_EXISTING,
    SUGGEST_VERSION: IPC_CHANNELS.CHANGELOG_SUGGEST_VERSION,
    SUGGEST_VERSION_FROM_COMMITS: IPC_CHANNELS.CHANGELOG_SUGGEST_VERSION_FROM_COMMITS,
    GET_BRANCHES: IPC_CHANNELS.CHANGELOG_GET_BRANCHES,
    GET_TAGS: IPC_CHANNELS.CHANGELOG_GET_TAGS,
    GET_COMMITS_PREVIEW: IPC_CHANNELS.CHANGELOG_GET_COMMITS_PREVIEW,
    SAVE_IMAGE: IPC_CHANNELS.CHANGELOG_SAVE_IMAGE,
    READ_LOCAL_IMAGE: IPC_CHANNELS.CHANGELOG_READ_LOCAL_IMAGE,
    GENERATION_PROGRESS: IPC_CHANNELS.CHANGELOG_GENERATION_PROGRESS,
    GENERATION_COMPLETE: IPC_CHANNELS.CHANGELOG_GENERATION_COMPLETE,
    GENERATION_ERROR: IPC_CHANNELS.CHANGELOG_GENERATION_ERROR,
  },

  insights: {
    GET_SESSION: IPC_CHANNELS.INSIGHTS_GET_SESSION,
    SEND_MESSAGE: IPC_CHANNELS.INSIGHTS_SEND_MESSAGE,
    CLEAR_SESSION: IPC_CHANNELS.INSIGHTS_CLEAR_SESSION,
    CREATE_TASK: IPC_CHANNELS.INSIGHTS_CREATE_TASK,
    LIST_SESSIONS: IPC_CHANNELS.INSIGHTS_LIST_SESSIONS,
    NEW_SESSION: IPC_CHANNELS.INSIGHTS_NEW_SESSION,
    SWITCH_SESSION: IPC_CHANNELS.INSIGHTS_SWITCH_SESSION,
    DELETE_SESSION: IPC_CHANNELS.INSIGHTS_DELETE_SESSION,
    RENAME_SESSION: IPC_CHANNELS.INSIGHTS_RENAME_SESSION,
    UPDATE_MODEL_CONFIG: IPC_CHANNELS.INSIGHTS_UPDATE_MODEL_CONFIG,
    STREAM_CHUNK: IPC_CHANNELS.INSIGHTS_STREAM_CHUNK,
    STATUS: IPC_CHANNELS.INSIGHTS_STATUS,
    ERROR: IPC_CHANNELS.INSIGHTS_ERROR,
    SESSION_UPDATED: IPC_CHANNELS.INSIGHTS_SESSION_UPDATED,
  },

  queue: {
    GET_RUNNING_TASKS_BY_PROFILE: IPC_CHANNELS.QUEUE_GET_RUNNING_TASKS_BY_PROFILE,
    GET_BEST_PROFILE_FOR_TASK: IPC_CHANNELS.QUEUE_GET_BEST_PROFILE_FOR_TASK,
    ASSIGN_PROFILE_TO_TASK: IPC_CHANNELS.QUEUE_ASSIGN_PROFILE_TO_TASK,
    UPDATE_TASK_SESSION: IPC_CHANNELS.QUEUE_UPDATE_TASK_SESSION,
    GET_TASK_SESSION: IPC_CHANNELS.QUEUE_GET_TASK_SESSION,
    PROFILE_SWAPPED: IPC_CHANNELS.QUEUE_PROFILE_SWAPPED,
    SESSION_CAPTURED: IPC_CHANNELS.QUEUE_SESSION_CAPTURED,
    BLOCKED_NO_PROFILES: IPC_CHANNELS.QUEUE_BLOCKED_NO_PROFILES,
  },

  app: {
    VERSION: IPC_CHANNELS.APP_VERSION,
    UPDATE_CHECK: IPC_CHANNELS.APP_UPDATE_CHECK,
    UPDATE_DOWNLOAD: IPC_CHANNELS.APP_UPDATE_DOWNLOAD,
    UPDATE_DOWNLOAD_STABLE: IPC_CHANNELS.APP_UPDATE_DOWNLOAD_STABLE,
    UPDATE_INSTALL: IPC_CHANNELS.APP_UPDATE_INSTALL,
    UPDATE_GET_VERSION: IPC_CHANNELS.APP_UPDATE_GET_VERSION,
    UPDATE_GET_DOWNLOADED: IPC_CHANNELS.APP_UPDATE_GET_DOWNLOADED,
    UPDATE_AVAILABLE: IPC_CHANNELS.APP_UPDATE_AVAILABLE,
    UPDATE_DOWNLOADED: IPC_CHANNELS.APP_UPDATE_DOWNLOADED,
    UPDATE_PROGRESS: IPC_CHANNELS.APP_UPDATE_PROGRESS,
    UPDATE_ERROR: IPC_CHANNELS.APP_UPDATE_ERROR,
    UPDATE_STABLE_DOWNGRADE: IPC_CHANNELS.APP_UPDATE_STABLE_DOWNGRADE,
    UPDATE_READONLY_VOLUME: IPC_CHANNELS.APP_UPDATE_READONLY_VOLUME,
  },

  debug: {
    GET_INFO: IPC_CHANNELS.DEBUG_GET_INFO,
    OPEN_LOGS_FOLDER: IPC_CHANNELS.DEBUG_OPEN_LOGS_FOLDER,
    COPY_DEBUG_INFO: IPC_CHANNELS.DEBUG_COPY_DEBUG_INFO,
    GET_RECENT_ERRORS: IPC_CHANNELS.DEBUG_GET_RECENT_ERRORS,
    LIST_LOG_FILES: IPC_CHANNELS.DEBUG_LIST_LOG_FILES,
    SIMULATE_RATE_LIMIT: IPC_CHANNELS.DEBUG_SIMULATE_RATE_LIMIT,
  },
} as const;

// ============================================
// Type exports
// ============================================

export type IPCNamespace = keyof typeof IPC_NS;

// ============================================
// Utilities
// ============================================

/**
 * Returns all channel string values for a given namespace.
 * Useful for logging, debugging, or auto-registering handlers.
 *
 * @example
 *   getChannelsByNamespace('terminal')
 *   // => ['terminal:create', 'terminal:destroy', ...]
 */
export function getChannelsByNamespace(ns: IPCNamespace): ChannelValue[] {
  const group = IPC_NS[ns];
  return Object.values(group) as ChannelValue[];
}

/**
 * Extracts the namespace prefix from a channel string.
 *
 * @example
 *   getNamespaceFromChannel('terminal:create') // => 'terminal'
 *   getNamespaceFromChannel('github:pr:list')  // => 'github'
 */
export function getNamespaceFromChannel(channel: string): string {
  return channel.split(':')[0];
}

/**
 * Returns a flat list of all IPC channel values grouped by namespace.
 * Useful for documentation or runtime channel validation.
 */
export function getAllNamespacedChannels(): Record<string, ChannelValue[]> {
  const result: Record<string, ChannelValue[]> = {};
  for (const ns of Object.keys(IPC_NS) as IPCNamespace[]) {
    result[ns] = getChannelsByNamespace(ns);
  }
  return result;
}
