"""
Quality Badge Generator
=======================

Génère des badges visuels et des rapports formatés pour les scores de qualité.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .quality_scorer import QualityScore


class QualityBadgeFormatter:
    """Formatte les scores de qualité en badges et rapports."""

    # Couleurs pour shields.io
    GRADE_COLORS = {
        'A+': 'brightgreen',
        'A': 'green',
        'A-': 'green',
        'B+': 'yellowgreen',
        'B': 'yellow',
        'B-': 'yellow',
        'C+': 'orange',
        'C': 'orange',
        'C-': 'orange',
        'D': 'red',
        'F': 'red',
    }

    def generate_shields_badge_url(self, score: QualityScore) -> str:
        """Génère une URL de badge shields.io."""
        color = self.GRADE_COLORS.get(score.grade, 'lightgrey')
        score_text = f"{score.overall_score:.0f}/100"
        return f"https://img.shields.io/badge/Quality-{score.grade}_{score_text}-{color}?style=flat-square"

    def generate_markdown_badge(self, score: QualityScore) -> str:
        """Génère un badge Markdown."""
        badge_url = self.generate_shields_badge_url(score)
        status = "✅ PASSING" if score.is_passing else "❌ FAILING"
        
        return f"![Code Quality]({badge_url}) **{status}**"

    def generate_markdown_summary(self, score: QualityScore) -> str:
        """Génère un résumé Markdown complet."""
        badge = self.generate_markdown_badge(score)
        
        md = f"""## 🧠 Code Quality Report

{badge}

### Summary
- **Score**: {score.overall_score:.1f}/100
- **Grade**: {score.grade}
- **Status**: {"✅ PASSING" if score.is_passing else "❌ FAILING"}
- **Total Issues**: {score.total_issues}
- **Critical Issues**: {score.critical_issues}

### Issues Breakdown

"""
        
        if score.total_issues == 0:
            md += "🎉 **No issues detected!** Great job!\n"
        else:
            # Grouper par sévérité
            by_severity = {}
            for issue in score.issues:
                severity = issue.severity.value
                if severity not in by_severity:
                    by_severity[severity] = []
                by_severity[severity].append(issue)
            
            severity_order = ['critical', 'high', 'medium', 'low']
            severity_icons = {
                'critical': '🚨',
                'high': '⚠️',
                'medium': '⚡',
                'low': 'ℹ️'
            }
            
            for severity in severity_order:
                if severity in by_severity:
                    issues = by_severity[severity]
                    icon = severity_icons.get(severity, '•')
                    md += f"#### {icon} {severity.upper()} ({len(issues)} issues)\n\n"
                    
                    for issue in issues[:5]:  # Max 5 par sévérité
                        md += f"- **{issue.title}**\n"
                        md += f"  - File: `{issue.file}`"
                        if issue.line:
                            md += f":{issue.line}"
                        md += "\n"
                        if issue.suggestion:
                            md += f"  - 💡 Suggestion: {issue.suggestion}\n"
                        md += "\n"
                    
                    if len(issues) > 5:
                        md += f"*... and {len(issues) - 5} more {severity} issues*\n\n"
        
        md += "\n---\n*Generated by Auto-Claude Quality Scorer*\n"
        
        return md

    def generate_terminal_output(self, score: QualityScore) -> str:
        """Génère un output formaté pour terminal."""
        lines = []
        lines.append("=" * 70)
        lines.append("  🧠 AI CODE REVIEW - SCORE DE QUALITÉ")
        lines.append("=" * 70)
        lines.append("")
        lines.append(f"  Score Global: {score.overall_score:.1f}/100 (Grade: {score.grade})")
        lines.append("")
        
        if score.is_passing:
            lines.append("  ✅ PASSED - Le code respecte les standards de qualité.")
        else:
            lines.append("  ❌ FAILED - Problèmes détectés.")
        
        lines.append("")
        lines.append("  Issues Détectées:")
        lines.append(f"    🚨 Critical: {score.critical_issues}")
        lines.append(f"    ⚠️  Total: {score.total_issues}")
        lines.append("")
        
        if score.issues:
            lines.append("  Détails des Issues:")
            for issue in score.issues[:10]:
                severity_icon = {
                    'critical': '🚨',
                    'high': '⚠️',
                    'medium': '⚡',
                    'low': 'ℹ️'
                }
                icon = severity_icon.get(issue.severity.value, '•')
                lines.append(f"    {icon} [{issue.severity.value}] {issue.title}")
                lines.append(f"      {issue.file}:{issue.line or '?'}")
                if issue.suggestion:
                    lines.append(f"      💡 {issue.suggestion}")
            
            if len(score.issues) > 10:
                lines.append(f"    ... et {len(score.issues) - 10} autres issues")
        
        lines.append("")
        lines.append("=" * 70)
        
        return "\n".join(lines)

    def generate_json_report(self, score: QualityScore) -> dict[str, Any]:
        """Génère un rapport JSON complet."""
        return {
            "score": score.overall_score,
            "grade": score.grade,
            "passing": score.is_passing,
            "total_issues": score.total_issues,
            "critical_issues": score.critical_issues,
            "badge_url": self.generate_shields_badge_url(score),
            "issues": [issue.to_dict() for issue in score.issues],
        }

    def save_markdown_report(self, score: QualityScore, output_path: Path) -> None:
        """Sauvegarde un rapport Markdown dans un fichier."""
        report = self.generate_markdown_summary(score)
        output_path.write_text(report, encoding='utf-8')

    def save_json_report(self, score: QualityScore, output_path: Path) -> None:
        """Sauvegarde un rapport JSON dans un fichier."""
        import json
        report = self.generate_json_report(score)
        output_path.write_text(json.dumps(report, indent=2), encoding='utf-8')

