"""
Mock API Server — Intercept and mock external API calls during sandbox simulation.

During a dry-run, network calls to external APIs are intercepted and
answered with plausible mock responses generated by a lightweight LLM
(or from static schema definitions).
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class MockStrategy(str, Enum):
    SCHEMA_BASED = "schema_based"
    LLM_GENERATED = "llm_generated"
    STATIC = "static"
    PASSTHROUGH = "passthrough"


@dataclass
class MockResponse:
    """A mocked API response."""

    status_code: int = 200
    body: dict[str, Any] | str = field(default_factory=dict)
    headers: dict[str, str] = field(
        default_factory=lambda: {"Content-Type": "application/json"}
    )
    strategy: MockStrategy = MockStrategy.SCHEMA_BASED
    latency_ms: float = 0.0


@dataclass
class InterceptedRequest:
    """A captured outbound request."""

    method: str
    url: str
    headers: dict[str, str] = field(default_factory=dict)
    body: str | None = None
    timestamp: float = 0.0


@dataclass
class MockRule:
    """A rule mapping a URL pattern to a mock response strategy."""

    url_pattern: str
    strategy: MockStrategy = MockStrategy.SCHEMA_BASED
    static_response: MockResponse | None = None
    schema: dict[str, Any] | None = None


class MockApiServer:
    """Generate mock responses for external API calls.

    Usage::

        server = MockApiServer()
        server.add_rule(MockRule(url_pattern="https://api.example.com/.*"))
        resp = server.handle_request(InterceptedRequest(method="GET", url="https://api.example.com/users"))
    """

    def __init__(self) -> None:
        self._rules: list[MockRule] = []
        self._request_log: list[InterceptedRequest] = []
        self._response_cache: dict[str, MockResponse] = {}

    @property
    def request_log(self) -> list[InterceptedRequest]:
        return list(self._request_log)

    def add_rule(self, rule: MockRule) -> None:
        self._rules.append(rule)

    def clear_rules(self) -> None:
        self._rules.clear()

    def handle_request(self, request: InterceptedRequest) -> MockResponse:
        """Route a request to the appropriate mock handler."""
        self._request_log.append(request)

        # Check cache
        cache_key = self._cache_key(request)
        if cache_key in self._response_cache:
            return self._response_cache[cache_key]

        # Find matching rule
        rule = self._find_rule(request.url)
        if rule is None:
            response = self._default_response(request)
        elif rule.strategy == MockStrategy.STATIC and rule.static_response:
            response = rule.static_response
        elif rule.strategy == MockStrategy.SCHEMA_BASED and rule.schema:
            response = self._generate_from_schema(rule.schema, request)
        elif rule.strategy == MockStrategy.PASSTHROUGH:
            response = MockResponse(
                status_code=200,
                body={"_passthrough": True, "_note": "Sandbox: passthrough disabled"},
            )
        else:
            response = self._generate_plausible(request)

        self._response_cache[cache_key] = response
        return response

    def get_stats(self) -> dict[str, int]:
        """Return request/response statistics."""
        return {
            "total_requests": len(self._request_log),
            "cached_responses": len(self._response_cache),
            "rules_count": len(self._rules),
        }

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _find_rule(self, url: str) -> MockRule | None:
        for rule in self._rules:
            if re.search(rule.url_pattern, url):
                return rule
        return None

    @staticmethod
    def _cache_key(request: InterceptedRequest) -> str:
        raw = f"{request.method}:{request.url}:{request.body or ''}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    @staticmethod
    def _generate_from_schema(
        schema: dict[str, Any], request: InterceptedRequest
    ) -> MockResponse:
        """Generate a response that conforms to the given JSON schema."""
        body = _build_from_schema(schema)
        return MockResponse(
            status_code=200,
            body=body,
            strategy=MockStrategy.SCHEMA_BASED,
        )

    @staticmethod
    def _generate_plausible(request: InterceptedRequest) -> MockResponse:
        """Generate a generic plausible response when no schema is available."""
        path_parts = request.url.rstrip("/").split("/")
        resource = path_parts[-1] if path_parts else "item"

        body: dict[str, Any] = {
            "id": 1,
            "status": "ok",
            "_sandbox": True,
            "_resource": resource,
        }

        if request.method.upper() == "POST":
            body["created"] = True
        elif request.method.upper() == "DELETE":
            body["deleted"] = True

        return MockResponse(
            status_code=200 if request.method.upper() != "DELETE" else 204,
            body=body,
            strategy=MockStrategy.LLM_GENERATED,
        )

    @staticmethod
    def _default_response(request: InterceptedRequest) -> MockResponse:
        return MockResponse(
            status_code=200,
            body={
                "_sandbox": True,
                "_note": f"No mock rule matched {request.url}",
                "data": None,
            },
        )


def _build_from_schema(schema: dict[str, Any]) -> Any:
    """Recursively build a value from a JSON Schema definition."""
    schema_type = schema.get("type", "object")

    if schema_type == "object":
        props = schema.get("properties", {})
        return {k: _build_from_schema(v) for k, v in props.items()}
    elif schema_type == "array":
        items = schema.get("items", {"type": "string"})
        return [_build_from_schema(items)]
    elif schema_type == "string":
        return schema.get("example", "mock_string")
    elif schema_type == "integer":
        return schema.get("example", 1)
    elif schema_type == "number":
        return schema.get("example", 1.0)
    elif schema_type == "boolean":
        return schema.get("example", True)
    else:
        return None
