"""Docker Compose Generator — Generates reproducible environments from captures.

Produces ``docker-compose.clone.yml``, ``.env.clone``, and ``seed.sh`` files
from an ``EnvironmentCapture``.

Example:
    >>> from environment.capturer import EnvironmentCapturer
    >>> from environment.generator import ComposeGenerator
    >>> capturer = EnvironmentCapturer(Path("/my/project"))
    >>> capture = capturer.capture_from_compose()
    >>> generator = ComposeGenerator(capture)
    >>> files = generator.write_all(Path(".auto-claude/environment"))
"""

import logging
import stat
from pathlib import Path
from typing import Any

from .capturer import EnvironmentCapture, ServiceCapture

logger = logging.getLogger(__name__)


class ComposeGenerator:
    """Generates docker-compose.yml and supporting files from a capture."""

    def __init__(self, capture: EnvironmentCapture) -> None:
        self.capture = capture

    def generate(self) -> str:
        """Generate docker-compose YAML content.

        Uses string templates to avoid a pyyaml dependency.

        Returns:
            docker-compose.yml content as a string.
        """
        lines = [
            "# Auto-generated by WorkPilot AI Environment Cloner",
            f"# Source: {self.capture.source}",
            f"# Captured: {self.capture.captured_at}",
            "",
            "services:",
        ]

        for service in self.capture.services:
            lines.extend(self._render_service(service))

        if self.capture.networks:
            lines.append("")
            lines.append("networks:")
            for net in self.capture.networks:
                lines.append(f"  {net}:")
                lines.append("    driver: bridge")

        if self.capture.volumes:
            lines.append("")
            lines.append("volumes:")
            for vol in self.capture.volumes:
                lines.append(f"  {vol}:")

        lines.append("")
        return "\n".join(lines)

    def generate_env_file(self) -> str:
        """Generate .env file content from captured env vars.

        Returns:
            .env file content with secrets replaced by placeholders.
        """
        lines = [
            "# Auto-generated by WorkPilot AI Environment Cloner",
            "# Replace <REPLACE_ME> values with actual secrets",
            "",
        ]

        # Project-level env vars
        for key, value in sorted(self.capture.env_vars.items()):
            lines.append(f"{key}={value}")

        # Service-level env vars (deduplicated)
        seen = set(self.capture.env_vars.keys())
        for service in self.capture.services:
            for key, value in sorted(service.environment.items()):
                if key not in seen:
                    lines.append(f"# [{service.name}]")
                    lines.append(f"{key}={value}")
                    seen.add(key)

        lines.append("")
        return "\n".join(lines)

    def generate_seed_script(self) -> str:
        """Generate a seed data script stub.

        Returns:
            Shell script content for database seeding.
        """
        db_services = [
            s for s in self.capture.services
            if any(
                kw in s.image.lower()
                for kw in ("postgres", "mysql", "mariadb", "mongo", "redis")
            )
        ]

        lines = [
            "#!/bin/bash",
            "# Auto-generated by WorkPilot AI Environment Cloner",
            "# Seed data script — customize for your project",
            "",
            'set -euo pipefail',
            "",
            'echo "Waiting for services to start..."',
            "sleep 5",
            "",
        ]

        if not db_services:
            lines.append("# No database services detected.")
            lines.append('echo "No databases to seed."')
        else:
            for service in db_services:
                lines.append(f"# --- {service.name} ({service.image}:{service.tag}) ---")
                if "postgres" in service.image.lower():
                    lines.append(f"# docker exec {service.name} psql -U ${{POSTGRES_USER:-postgres}} -d ${{POSTGRES_DB:-app}} -f /seed.sql")
                elif "mysql" in service.image.lower() or "mariadb" in service.image.lower():
                    lines.append(f"# docker exec {service.name} mysql -u ${{MYSQL_USER:-root}} -p${{MYSQL_PASSWORD:-root}} ${{MYSQL_DATABASE:-app}} < /seed.sql")
                elif "mongo" in service.image.lower():
                    lines.append(f"# docker exec {service.name} mongosh --eval 'db.getSiblingDB(\"app\").createCollection(\"seed\")'")
                elif "redis" in service.image.lower():
                    lines.append(f"# docker exec {service.name} redis-cli PING")
                lines.append("")

        lines.append('echo "Seeding complete."')
        lines.append("")
        return "\n".join(lines)

    def write_all(self, output_dir: Path) -> list[Path]:
        """Write all generated files to the output directory.

        Args:
            output_dir: Directory to write files to.

        Returns:
            List of written file paths.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        files: list[Path] = []

        # docker-compose.clone.yml
        compose_path = output_dir / "docker-compose.clone.yml"
        compose_path.write_text(self.generate(), encoding="utf-8")
        files.append(compose_path)
        logger.info("Generated %s", compose_path)

        # .env.clone
        env_path = output_dir / ".env.clone"
        env_path.write_text(self.generate_env_file(), encoding="utf-8")
        files.append(env_path)
        logger.info("Generated %s", env_path)

        # seed.sh
        seed_path = output_dir / "seed.sh"
        seed_path.write_text(self.generate_seed_script(), encoding="utf-8")
        try:
            seed_path.chmod(seed_path.stat().st_mode | stat.S_IEXEC)
        except OSError:
            pass  # Windows doesn't support chmod
        files.append(seed_path)
        logger.info("Generated %s", seed_path)

        return files

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _render_service(self, service: ServiceCapture) -> list[str]:
        """Render a single service as YAML lines."""
        lines = [f"  {service.name}:"]

        if service.image:
            image_ref = f"{service.image}:{service.tag}" if service.tag else service.image
            lines.append(f"    image: {image_ref}")

        if service.command:
            lines.append(f"    command: {service.command}")

        if service.ports:
            lines.append("    ports:")
            for p in service.ports:
                lines.append(f'      - "{p["host"]}:{p["container"]}"')

        if service.environment:
            lines.append("    environment:")
            for k, v in sorted(service.environment.items()):
                lines.append(f"      {k}: {v}")

        if service.volumes:
            lines.append("    volumes:")
            for v in service.volumes:
                lines.append(f"      - {v}")

        if service.depends_on:
            lines.append("    depends_on:")
            for dep in service.depends_on:
                lines.append(f"      - {dep}")

        if service.health_check:
            hc = service.health_check
            lines.append("    healthcheck:")
            if hc.get("test"):
                test = hc["test"]
                if isinstance(test, list):
                    test = " ".join(str(t) for t in test)
                lines.append(f"      test: {test}")
            if hc.get("interval"):
                lines.append(f"      interval: {hc['interval']}")
            if hc.get("timeout"):
                lines.append(f"      timeout: {hc['timeout']}")
            if hc.get("retries"):
                lines.append(f"      retries: {hc['retries']}")

        lines.append("")
        return lines
