"""
Data models for the Live Development Companion.
"""

import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class SuggestionType(str, Enum):
    """Type of proactive suggestion."""

    BUG_DETECTION = "bug_detection"
    DUPLICATE_CODE = "duplicate_code"
    MISSING_UPDATE = "missing_update"
    CONTRACT_VIOLATION = "contract_violation"
    PERFORMANCE_ISSUE = "performance_issue"
    SECURITY_ISSUE = "security_issue"
    MISSING_TEST = "missing_test"
    REFACTOR_OPPORTUNITY = "refactor_opportunity"
    IMPORT_SUGGESTION = "import_suggestion"
    CONVENTION_MISMATCH = "convention_mismatch"
    GENERAL = "general"


class SuggestionPriority(str, Enum):
    """Priority level for suggestions."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class TakeoverStatus(str, Enum):
    """Status of a takeover proposal."""

    PROPOSED = "proposed"
    ACCEPTED = "accepted"
    DECLINED = "declined"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


@dataclass
class FileChangeEvent:
    """A file change detected by the watcher."""

    file_path: str
    change_type: str  # created | modified | deleted | renamed
    diff: str = ""
    language: str = ""
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FileChangeEvent":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class LiveSuggestion:
    """A proactive suggestion generated by the companion."""

    suggestion_id: str
    suggestion_type: SuggestionType
    priority: SuggestionPriority
    title: str
    description: str
    file_path: str
    line_start: int = 0
    line_end: int = 0
    code_fix: str = ""
    related_files: list[str] = field(default_factory=list)
    confidence: float = 0.0
    created_at: str = ""
    status: str = "active"  # active | applied | dismissed | expired

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()
        if isinstance(self.suggestion_type, str):
            self.suggestion_type = SuggestionType(self.suggestion_type)
        if isinstance(self.priority, str):
            self.priority = SuggestionPriority(self.priority)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["suggestion_type"] = self.suggestion_type.value
        d["priority"] = self.priority.value
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LiveSuggestion":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    @staticmethod
    def generate_id() -> str:
        return f"sug-{uuid.uuid4().hex[:12]}"


@dataclass
class TakeoverProposal:
    """A proposal for the AI to take over a file the developer is stuck on."""

    proposal_id: str
    file_path: str
    reason: str
    description: str
    inactivity_seconds: int = 0
    complexity_score: float = 0.0
    status: TakeoverStatus = TakeoverStatus.PROPOSED
    ai_plan: str = ""
    ai_result_summary: str = ""
    created_at: str = ""

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()
        if isinstance(self.status, str):
            self.status = TakeoverStatus(self.status)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["status"] = self.status.value
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TakeoverProposal":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    @staticmethod
    def generate_id() -> str:
        return f"tkv-{uuid.uuid4().hex[:12]}"


@dataclass
class CompanionConfig:
    """Configuration for the Live Companion."""

    enabled: bool = False
    watch_debounce_ms: int = 1500
    suggestion_enabled: bool = True
    takeover_enabled: bool = True
    takeover_inactivity_seconds: int = 120
    min_suggestion_confidence: float = 0.5
    max_suggestions_per_file: int = 5
    watch_patterns: list[str] = field(
        default_factory=lambda: [
            "**/*.ts",
            "**/*.tsx",
            "**/*.js",
            "**/*.jsx",
            "**/*.py",
            "**/*.rs",
            "**/*.go",
            "**/*.java",
            "**/*.cs",
            "**/*.rb",
            "**/*.php",
            "**/*.vue",
            "**/*.svelte",
        ]
    )
    ignore_patterns: list[str] = field(
        default_factory=lambda: [
            "**/node_modules/**",
            "**/.git/**",
            "**/dist/**",
            "**/build/**",
            "**/__pycache__/**",
            "**/venv/**",
            "**/.venv/**",
            "**/*.min.js",
            "**/*.map",
        ]
    )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CompanionConfig":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class CompanionState:
    """Runtime state of the Live Companion."""

    active: bool = False
    watching_project: str = ""
    files_watched: int = 0
    changes_detected: int = 0
    suggestions_generated: int = 0
    suggestions_accepted: int = 0
    takeovers_proposed: int = 0
    takeovers_accepted: int = 0
    started_at: str = ""
    last_change_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CompanionState":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})
