"""
Test Generator — Generate regression tests from parsed incidents.

Produces framework-appropriate test code (pytest, Jest, Vitest, JUnit,
Go testing, xUnit, cargo test) that reproduces the incident state and
asserts the error occurs.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum

from .incident_parser import Incident, StackFrame

logger = logging.getLogger(__name__)


class TestFramework(str, Enum):
    PYTEST = "pytest"
    UNITTEST = "unittest"
    JEST = "jest"
    VITEST = "vitest"
    MOCHA = "mocha"
    JUNIT5 = "junit5"
    TESTNG = "testng"
    GO_TEST = "go_test"
    XUNIT = "xunit"
    NUNIT = "nunit"
    CARGO_TEST = "cargo_test"


class TestStatus(str, Enum):
    RED = "red"
    GREEN = "green"
    SKIPPED = "skipped"


@dataclass
class GeneratedTest:
    """A regression test generated from an incident."""

    incident_id: str
    framework: TestFramework
    test_name: str
    test_code: str
    file_path: str
    status: TestStatus = TestStatus.RED
    target_file: str = ""
    target_function: str = ""
    fixtures: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)


class TestGenerator:
    """Generate regression tests from production incidents.

    Usage::

        gen = TestGenerator()
        test = gen.generate(incident, framework=TestFramework.PYTEST)
    """

    def generate(
        self,
        incident: Incident,
        framework: TestFramework = TestFramework.PYTEST,
        project_root: str = "",
    ) -> GeneratedTest:
        """Generate a regression test for the given incident."""
        generators = {
            TestFramework.PYTEST: self._gen_pytest,
            TestFramework.UNITTEST: self._gen_unittest,
            TestFramework.JEST: self._gen_jest,
            TestFramework.VITEST: self._gen_vitest,
            TestFramework.MOCHA: self._gen_mocha,
            TestFramework.JUNIT5: self._gen_junit5,
            TestFramework.GO_TEST: self._gen_go_test,
            TestFramework.XUNIT: self._gen_xunit,
            TestFramework.CARGO_TEST: self._gen_cargo_test,
        }
        gen_fn = generators.get(framework, self._gen_pytest)
        return gen_fn(incident, project_root)

    def detect_framework(self, project_files: list[str]) -> TestFramework:
        """Detect the test framework from project file listing."""
        file_set = set(f.lower() for f in project_files)

        if "pytest.ini" in file_set or "pyproject.toml" in file_set or "conftest.py" in file_set:
            return TestFramework.PYTEST
        if "jest.config.js" in file_set or "jest.config.ts" in file_set:
            return TestFramework.JEST
        if "vitest.config.ts" in file_set or "vitest.config.js" in file_set:
            return TestFramework.VITEST
        if "pom.xml" in file_set or "build.gradle" in file_set:
            return TestFramework.JUNIT5
        if "go.mod" in file_set:
            return TestFramework.GO_TEST
        if "cargo.toml" in file_set:
            return TestFramework.CARGO_TEST
        if any(f.endswith(".csproj") for f in file_set):
            return TestFramework.XUNIT
        if ".mocharc.yml" in file_set or ".mocharc.js" in file_set:
            return TestFramework.MOCHA

        return TestFramework.PYTEST

    # ------------------------------------------------------------------
    # Framework-specific generators
    # ------------------------------------------------------------------

    def _gen_pytest(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        target = incident.faulting_function or "unknown_function"
        target_file = incident.faulting_file or ""
        import_path = _file_to_module(target_file)

        code = f'''"""Regression test for incident {incident.id}.

Auto-generated by Regression Guardian.
Incident: {incident.title}
Exception: {incident.exception_type}: {incident.exception_message}
"""
import pytest


def test_regression_{func}():
    """Regression test — should fail until the bug is fixed.

    Incident: {incident.id}
    Source: {incident.source.value}
    """
    # TODO: Import the faulting module
    # from {import_path} import {target}

    # TODO: Set up the state that reproduces the incident
    # Use fixtures from fixture_builder if available

    # Assert that the error condition is handled correctly
    # Before fix: this test should FAIL (reproducing the bug)
    # After fix: this test should PASS (confirming the fix)
    pytest.skip("Skeleton test — fill in reproduction logic from incident context")
'''
        file_path = f"tests/regression/test_incident_{func}.py"

        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.PYTEST,
            test_name=f"test_regression_{func}",
            test_code=code,
            file_path=file_path,
            target_file=target_file,
            target_function=target,
            tags=["regression", incident.source.value],
        )

    def _gen_unittest(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        code = f'''"""Regression test for incident {incident.id}."""
import unittest


class TestRegression{func.title().replace("_", "")}(unittest.TestCase):
    """Regression test — incident {incident.id}."""

    def test_regression_{func}(self):
        """Reproduces: {incident.exception_type}: {incident.exception_message}"""
        self.skipTest("Skeleton test — fill in reproduction logic")


if __name__ == "__main__":
    unittest.main()
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.UNITTEST,
            test_name=f"test_regression_{func}",
            test_code=code,
            file_path=f"tests/regression/test_incident_{func}.py",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_jest(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        code = f'''/**
 * Regression test for incident {incident.id}.
 * Auto-generated by Regression Guardian.
 *
 * {incident.exception_type}: {incident.exception_message}
 */
describe("Regression: incident {incident.id}", () => {{
  it("should handle the error condition correctly", () => {{
    // TODO: Import the faulting module
    // TODO: Set up the state that reproduces the incident

    // Before fix: this test should FAIL
    // After fix: this test should PASS
    expect(true).toBe(true); // placeholder
  }});
}});
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.JEST,
            test_name=f"regression_incident_{func}",
            test_code=code,
            file_path=f"tests/regression/incident_{func}.test.ts",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_vitest(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        code = f'''/**
 * Regression test for incident {incident.id}.
 * Auto-generated by Regression Guardian.
 */
import {{ describe, it, expect }} from "vitest";

describe("Regression: incident {incident.id}", () => {{
  it("should handle the error condition correctly", () => {{
    // TODO: Reproduce the incident state
    expect(true).toBe(true); // placeholder
  }});
}});
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.VITEST,
            test_name=f"regression_incident_{func}",
            test_code=code,
            file_path=f"tests/regression/incident_{func}.test.ts",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_mocha(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        code = f'''const assert = require("assert");

describe("Regression: incident {incident.id}", function () {{
  it("should handle the error condition correctly", function () {{
    // TODO: Reproduce the incident state
    assert.ok(true); // placeholder
  }});
}});
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.MOCHA,
            test_name=f"regression_incident_{func}",
            test_code=code,
            file_path=f"test/regression/incident_{func}.test.js",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_junit5(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        class_name = func.title().replace("_", "")
        code = f'''package regression;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Regression test for incident {incident.id}.
 * Auto-generated by Regression Guardian.
 */
class Regression{class_name}Test {{

    @Test
    @Disabled("Skeleton test — fill in reproduction logic")
    void testRegression_{func}() {{
        // TODO: Reproduce the incident state
        // {incident.exception_type}: {incident.exception_message}
        assertTrue(true);
    }}
}}
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.JUNIT5,
            test_name=f"testRegression_{func}",
            test_code=code,
            file_path=f"src/test/java/regression/Regression{class_name}Test.java",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_go_test(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        go_func = "".join(w.title() for w in func.split("_"))
        code = f'''package regression

import "testing"

// TestRegression{go_func} is a regression test for incident {incident.id}.
// Auto-generated by Regression Guardian.
// {incident.exception_type}: {incident.exception_message}
func TestRegression{go_func}(t *testing.T) {{
\tt.Skip("Skeleton test — fill in reproduction logic")
\t// TODO: Reproduce the incident state
}}
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.GO_TEST,
            test_name=f"TestRegression{go_func}",
            test_code=code,
            file_path=f"regression/incident_{func}_test.go",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_xunit(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        class_name = func.title().replace("_", "")
        code = f'''using Xunit;

/// <summary>
/// Regression test for incident {incident.id}.
/// Auto-generated by Regression Guardian.
/// </summary>
public class Regression{class_name}Tests
{{
    [Fact(Skip = "Skeleton test — fill in reproduction logic")]
    public void TestRegression_{func}()
    {{
        // TODO: Reproduce the incident state
        // {incident.exception_type}: {incident.exception_message}
        Assert.True(true);
    }}
}}
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.XUNIT,
            test_name=f"TestRegression_{func}",
            test_code=code,
            file_path=f"Tests/Regression/Regression{class_name}Tests.cs",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )

    def _gen_cargo_test(self, incident: Incident, project_root: str) -> GeneratedTest:
        func = _safe_function_name(incident)
        code = f'''//! Regression test for incident {incident.id}.
//! Auto-generated by Regression Guardian.

#[cfg(test)]
mod regression_tests {{
    #[test]
    #[ignore = "Skeleton test — fill in reproduction logic"]
    fn test_regression_{func}() {{
        // TODO: Reproduce the incident state
        // {incident.exception_type}: {incident.exception_message}
        assert!(true);
    }}
}}
'''
        return GeneratedTest(
            incident_id=incident.id,
            framework=TestFramework.CARGO_TEST,
            test_name=f"test_regression_{func}",
            test_code=code,
            file_path=f"tests/regression/incident_{func}.rs",
            target_file=incident.faulting_file or "",
            target_function=incident.faulting_function or "",
            tags=["regression", incident.source.value],
        )


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _safe_function_name(incident: Incident) -> str:
    """Derive a safe function name from the incident."""
    import re as _re
    base = incident.faulting_function or incident.exception_type or incident.id
    safe = _re.sub(r"[^a-zA-Z0-9]", "_", base).strip("_").lower()
    return safe[:60] or "unknown"


def _file_to_module(filepath: str) -> str:
    """Convert a file path to a Python import path."""
    return filepath.replace("/", ".").replace("\\", ".").removesuffix(".py")
