"""Postman connector — High-level interface for API collection management.

Provides methods for listing/importing collections, managing environments,
generating collections from endpoints, and running collection tests
against APIs generated by WorkPilot AI agents.

Example:
    >>> from src.connectors.postman import PostmanConnector
    >>> connector = PostmanConnector.from_env()
    >>> collections = connector.list_collections(workspace_id="ws-123")
    >>> collection = connector.get_collection("col-456")
"""

import logging
from typing import Any

from src.connectors.postman.client import PostmanClient
from src.connectors.postman.models import (
    PostmanCollection,
    PostmanCollectionRun,
    PostmanEnvironment,
    PostmanRequest,
    PostmanTestResult,
    PostmanWorkspace,
)

logger = logging.getLogger(__name__)


class PostmanConnector:
    """Unified connector for Postman API collection management.

    Provides high-level methods for interacting with Postman including
    collection import/export, environment sync, automatic collection
    generation from API endpoints, and test execution.

    Attributes:
        _client: The underlying Postman HTTP client.

    Example:
        >>> connector = PostmanConnector.from_env()
        >>> workspaces = connector.list_workspaces()
        >>> collections = connector.list_collections(workspaces[0].workspace_id)
    """

    def __init__(self, client: PostmanClient) -> None:
        """Initialize the Postman connector.

        Args:
            client: A PostmanClient instance. Does not need to be
                connected yet — call ``connect()`` to authenticate.
        """
        self._client = client

    @classmethod
    def from_env(cls) -> "PostmanConnector":
        """Create a connector from environment variables and connect.

        Reads ``POSTMAN_API_KEY`` from the environment, creates and
        connects the client.

        Returns:
            A connected PostmanConnector instance.

        Raises:
            PostmanConfigurationError: If required env vars are missing.
            PostmanAuthenticationError: If authentication fails.
        """
        client = PostmanClient.from_env()
        return cls(client)

    def connect(self) -> None:
        """Establish an authenticated connection to Postman.

        Raises:
            PostmanAuthenticationError: If the API key is invalid.
            PostmanAPIError: If the server is unreachable.
        """
        self._client.connect()

    def disconnect(self) -> None:
        """Close the connection to Postman."""
        self._client.disconnect()

    @property
    def is_connected(self) -> bool:
        """Check whether the connector has an active connection."""
        return self._client.is_connected

    def get_connection_info(self) -> dict[str, str]:
        """Get information about the current connection."""
        return self._client.get_connection_info()

    # ── Workspace operations ─────────────────────────────────────────

    def list_workspaces(self) -> list[PostmanWorkspace]:
        """List all workspaces accessible to the authenticated user.

        Returns:
            A list of PostmanWorkspace objects.

        Raises:
            PostmanAPIError: If the API call fails.
        """
        logger.info("Listing Postman workspaces.")

        data = self._client.get("/workspaces")
        workspaces_data = data.get("workspaces", [])
        workspaces = [PostmanWorkspace.from_api_response(w) for w in workspaces_data]

        logger.info("Found %d workspaces.", len(workspaces))
        return workspaces

    # ── Collection operations ────────────────────────────────────────

    def list_collections(
        self,
        workspace_id: str | None = None,
    ) -> list[PostmanCollection]:
        """List collections, optionally filtered by workspace.

        Args:
            workspace_id: Optional workspace ID to filter by.

        Returns:
            A list of PostmanCollection objects.

        Raises:
            PostmanAPIError: If the API call fails.
        """
        logger.info("Listing Postman collections (workspace=%s).", workspace_id)

        params = {}
        if workspace_id:
            params["workspace"] = workspace_id

        data = self._client.get("/collections", params=params)
        collections_data = data.get("collections", [])
        collections = [
            PostmanCollection.from_api_response(c) for c in collections_data
        ]

        logger.info("Found %d collections.", len(collections))
        return collections

    def get_collection(self, collection_id: str) -> dict[str, Any]:
        """Get the full details of a collection including all requests.

        Args:
            collection_id: The collection's unique ID or UID.

        Returns:
            The full collection data dictionary including items/requests.

        Raises:
            PostmanCollectionNotFoundError: If the collection does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Getting collection '%s'.", collection_id)

        data = self._client.get(f"/collections/{collection_id}")
        return data.get("collection", {})

    def get_collection_requests(
        self,
        collection_id: str,
    ) -> list[PostmanRequest]:
        """Extract all requests from a collection.

        Recursively traverses the collection tree to extract all
        request items.

        Args:
            collection_id: The collection's unique ID or UID.

        Returns:
            A flat list of PostmanRequest objects.

        Raises:
            PostmanCollectionNotFoundError: If the collection does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Extracting requests from collection '%s'.", collection_id)

        collection = self.get_collection(collection_id)
        items = collection.get("item", [])

        requests_list: list[PostmanRequest] = []
        self._extract_requests(items, requests_list)

        logger.info(
            "Extracted %d requests from collection '%s'.",
            len(requests_list),
            collection_id,
        )
        return requests_list

    def _extract_requests(
        self,
        items: list[dict[str, Any]],
        result: list[PostmanRequest],
        folder_id: str | None = None,
    ) -> None:
        """Recursively extract requests from collection items.

        Args:
            items: List of collection items (requests or folders).
            result: Accumulator list for extracted requests.
            folder_id: Parent folder ID for context.
        """
        for item in items:
            if "item" in item:
                # This is a folder — recurse
                self._extract_requests(
                    item["item"], result, folder_id=item.get("id")
                )
            elif "request" in item:
                req = PostmanRequest.from_api_response(item)
                req.folder_id = folder_id
                result.append(req)

    def import_collection_as_spec(
        self,
        collection_id: str,
    ) -> list[dict[str, Any]]:
        """Import a Postman collection as API specification entries.

        Converts collection requests into a format suitable for use
        as API specifications within WorkPilot AI.

        Args:
            collection_id: The collection ID.

        Returns:
            A list of API endpoint specification dictionaries.

        Raises:
            PostmanCollectionNotFoundError: If the collection does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Importing collection '%s' as API spec.", collection_id)

        requests_list = self.get_collection_requests(collection_id)

        specs = []
        for req in requests_list:
            specs.append({
                "name": req.name,
                "method": req.method,
                "url": req.url,
                "description": req.description,
                "headers": req.headers,
                "body": req.body,
                "source": "postman",
                "source_id": req.request_id,
            })

        logger.info("Imported %d endpoint specs.", len(specs))
        return specs

    # ── Collection generation ────────────────────────────────────────

    def generate_collection_from_endpoints(
        self,
        workspace_id: str,
        collection_name: str,
        endpoints: list[dict[str, Any]],
        base_url: str = "{{base_url}}",
    ) -> PostmanCollection:
        """Generate a Postman collection from a list of API endpoints.

        Creates a new collection in the specified workspace with
        requests for each endpoint.

        Args:
            workspace_id: The workspace to create the collection in.
            collection_name: Name for the new collection.
            endpoints: List of endpoint dicts with keys:
                ``'name'``, ``'method'``, ``'path'``, ``'description'``,
                ``'headers'``, ``'body'``.
            base_url: The base URL variable. Defaults to ``{{base_url}}``.

        Returns:
            The created PostmanCollection object.

        Raises:
            PostmanAPIError: If the API call fails.
        """
        logger.info(
            "Generating collection '%s' with %d endpoints.",
            collection_name,
            len(endpoints),
        )

        items = []
        for ep in endpoints:
            path = ep.get("path", "/")
            method = ep.get("method", "GET").upper()
            url = f"{base_url}{path}"

            item: dict[str, Any] = {
                "name": ep.get("name", f"{method} {path}"),
                "request": {
                    "method": method,
                    "header": ep.get("headers", []),
                    "url": {
                        "raw": url,
                        "host": [base_url],
                        "path": [p for p in path.split("/") if p],
                    },
                },
            }

            if ep.get("description"):
                item["request"]["description"] = ep["description"]

            body = ep.get("body")
            if body:
                item["request"]["body"] = {
                    "mode": "raw",
                    "raw": body if isinstance(body, str) else str(body),
                    "options": {"raw": {"language": "json"}},
                }

            # Add basic test script
            item["event"] = [
                {
                    "listen": "test",
                    "script": {
                        "type": "text/javascript",
                        "exec": [
                            "pm.test('Status code is successful', function () {",
                            "    pm.expect(pm.response.code).to.be.within(200, 299);",
                            "});",
                            "",
                            "pm.test('Response time is acceptable', function () {",
                            "    pm.expect(pm.response.responseTime).to.be.below(2000);",
                            "});",
                        ],
                    },
                }
            ]

            items.append(item)

        collection_payload = {
            "collection": {
                "info": {
                    "name": collection_name,
                    "description": f"Auto-generated by WorkPilot AI for {collection_name}",
                    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
                },
                "item": items,
                "variable": [
                    {
                        "key": "base_url",
                        "value": "http://localhost:3000",
                        "description": "Base URL for the API",
                    }
                ],
            },
            "workspace": workspace_id,
        }

        data = self._client.post("/collections", json_data=collection_payload)
        collection_data = data.get("collection", {})

        logger.info("Created collection '%s'.", collection_data.get("id", ""))
        return PostmanCollection.from_api_response(collection_data)

    # ── Environment operations ───────────────────────────────────────

    def list_environments(
        self,
        workspace_id: str | None = None,
    ) -> list[PostmanEnvironment]:
        """List environments, optionally filtered by workspace.

        Args:
            workspace_id: Optional workspace ID to filter by.

        Returns:
            A list of PostmanEnvironment objects.

        Raises:
            PostmanAPIError: If the API call fails.
        """
        logger.info("Listing Postman environments.")

        params = {}
        if workspace_id:
            params["workspace"] = workspace_id

        data = self._client.get("/environments", params=params)
        envs_data = data.get("environments", [])
        environments = [PostmanEnvironment.from_api_response(e) for e in envs_data]

        logger.info("Found %d environments.", len(environments))
        return environments

    def get_environment(self, environment_id: str) -> PostmanEnvironment:
        """Get details of a specific environment.

        Args:
            environment_id: The environment's unique ID.

        Returns:
            A PostmanEnvironment object.

        Raises:
            PostmanEnvironmentNotFoundError: If the environment does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Getting environment '%s'.", environment_id)

        data = self._client.get(f"/environments/{environment_id}")
        env_data = data.get("environment", {})
        return PostmanEnvironment.from_api_response(env_data)

    def sync_environment(
        self,
        environment_id: str,
        variables: dict[str, str],
    ) -> PostmanEnvironment:
        """Synchronize project configuration variables to a Postman environment.

        Updates the environment with the given variable key-value pairs.
        Existing variables with the same keys are updated; new variables
        are added.

        Args:
            environment_id: The environment ID.
            variables: Dictionary of variable names to values.

        Returns:
            The updated PostmanEnvironment.

        Raises:
            PostmanEnvironmentNotFoundError: If the environment does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info(
            "Syncing %d variables to environment '%s'.",
            len(variables),
            environment_id,
        )

        values = [
            {"key": k, "value": v, "enabled": True, "type": "default"}
            for k, v in variables.items()
        ]

        self._client.put(
            f"/environments/{environment_id}",
            json_data={
                "environment": {
                    "values": values,
                }
            },
        )

        return self.get_environment(environment_id)

    # ── Test execution simulation ────────────────────────────────────

    def validate_collection_structure(
        self,
        collection_id: str,
    ) -> PostmanCollectionRun:
        """Validate the structure and test scripts of a collection.

        Performs a dry-run validation of the collection by checking
        that all requests have valid URLs, methods, and test scripts.
        This does NOT execute HTTP requests.

        Args:
            collection_id: The collection ID.

        Returns:
            A PostmanCollectionRun with structural validation results.

        Raises:
            PostmanCollectionNotFoundError: If the collection does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Validating collection '%s'.", collection_id)

        requests_list = self.get_collection_requests(collection_id)

        results: list[PostmanTestResult] = []
        passed = 0
        failed = 0

        for req in requests_list:
            # Validate URL
            has_url = bool(req.url and req.url.strip())
            results.append(PostmanTestResult(
                request_name=req.name,
                test_name="Has valid URL",
                passed=has_url,
                error_message="" if has_url else "Request URL is empty",
            ))
            if has_url:
                passed += 1
            else:
                failed += 1

            # Validate method
            valid_methods = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}
            has_method = req.method.upper() in valid_methods
            results.append(PostmanTestResult(
                request_name=req.name,
                test_name="Has valid HTTP method",
                passed=has_method,
                error_message="" if has_method else f"Invalid method: {req.method}",
            ))
            if has_method:
                passed += 1
            else:
                failed += 1

        run = PostmanCollectionRun(
            collection_id=collection_id,
            total_tests=passed + failed,
            passed_tests=passed,
            failed_tests=failed,
            total_requests=len(requests_list),
            results=results,
        )

        logger.info(
            "Validation for '%s': %d/%d tests passed (%.1f%%).",
            collection_id,
            run.passed_tests,
            run.total_tests,
            run.success_rate,
        )
        return run

    # ── Convenience / aggregation ────────────────────────────────────

    def get_collection_summary(
        self,
        collection_id: str,
    ) -> dict[str, Any]:
        """Get a summary of a collection for dashboard display.

        Args:
            collection_id: The collection ID.

        Returns:
            A dictionary with collection metadata and request summary.

        Raises:
            PostmanCollectionNotFoundError: If the collection does not exist.
            PostmanAPIError: If the API call fails.
        """
        logger.info("Building collection summary for '%s'.", collection_id)

        collection = self.get_collection(collection_id)
        requests_list = self.get_collection_requests(collection_id)

        info = collection.get("info", {})
        methods_count: dict[str, int] = {}
        for req in requests_list:
            methods_count[req.method] = methods_count.get(req.method, 0) + 1

        return {
            "collection_id": collection_id,
            "name": info.get("name", ""),
            "description": info.get("description", ""),
            "total_requests": len(requests_list),
            "methods": methods_count,
            "requests": [
                {
                    "name": r.name,
                    "method": r.method,
                    "url": r.url,
                }
                for r in requests_list
            ],
        }
